/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
/** 勿手改：由 elegant-router 生成的路由元数据数组；变更请运行项目约定的路由生成命令。 */

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      keepAlive: true
    }
  },
  {
    name: 'advanced-modules',
    path: '/advanced-modules',
    component: 'layout.base$view.advanced-modules',
    meta: {
      title: 'advanced-modules',
      i18nKey: 'route.advanced-modules',
      icon: 'mdi:puzzle-outline',
      order: 70,
      keepAlive: true
    }
  },
  {
    name: 'choose-company',
    path: '/choose-company',
    component: 'layout.blank$view.choose-company',
    meta: {
      title: 'choose-company',
      i18nKey: 'route.choose-company',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'company-address',
    path: '/company-address',
    component: 'layout.base$view.company-address',
    meta: {
      title: 'company-address',
      i18nKey: 'route.company-address',
      order: 60,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 80,
      hideInMenu: true,
      keepAlive: true
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        component: 'view.function_hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 2,
          keepAlive: true
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child',
              keepAlive: true
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child',
              keepAlive: true
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child',
              keepAlive: true
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab',
          keepAlive: true
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3,
          keepAlive: true
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 5,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 1,
          keepAlive: true
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 4,
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      keepAlive: false
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base$view.log',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      icon: 'mdi:folder-text-outline',
      order: 30,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true,
      keepAlive: false
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 90,
      hideInMenu: true,
      roles: ['R_ADMIN'],
      keepAlive: true
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      keepAlive: true
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          keepAlive: true
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child',
              keepAlive: true
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          keepAlive: true
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child',
              keepAlive: true
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home',
                  keepAlive: true
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'notify',
    path: '/notify',
    component: 'layout.base$view.notify',
    meta: {
      title: 'notify',
      i18nKey: 'route.notify',
      order: 50,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'org',
    path: '/org',
    component: 'layout.base$view.org',
    meta: {
      title: 'org',
      i18nKey: 'route.org',
      icon: 'mdi:sitemap-outline',
      order: 20,
      keepAlive: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 10,
      keepAlive: true
    },
    children: [
      {
        name: 'system_branch',
        path: '/system/branch',
        component: 'view.system_branch',
        meta: {
          title: 'system_branch',
          i18nKey: 'route.system_branch',
          keepAlive: true
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          icon: 'mdi:menu',
          order: 3,
          keepAlive: true
        }
      },
      {
        name: 'system_notify-scene',
        path: '/system/notify-scene',
        component: 'view.system_notify-scene',
        meta: {
          title: 'system_notify-scene',
          i18nKey: 'route.system_notify-scene',
          keepAlive: true
        }
      },
      {
        name: 'system_notify-trace',
        path: '/system/notify-trace',
        component: 'view.system_notify-trace',
        meta: {
          title: 'system_notify-trace',
          i18nKey: 'route.system_notify-trace',
          keepAlive: true
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'mdi:account-key-outline',
          order: 2,
          keepAlive: true
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-outline',
          order: 1,
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'work-order',
    path: '/work-order',
    component: 'layout.base$view.work-order',
    meta: {
      title: 'work-order',
      i18nKey: 'route.work-order',
      order: 40,
      hideInMenu: true,
      keepAlive: true
    }
  }
];
